<template>
  <div>
    <template v-if="$page.project.template == 'ProjectB'">
      <!-- Layout for webdesign projects -->
      <Layout :title="$page.project.title">
        <article class="project-post">
          <h1 v-if="$page.project.template === 'ProjectB'">hey: {{ $page.project.template }}</h1>
          <g-image class="thumbnail" :src="$page.project.thumbnail" :alt="$page.project.title" />

          <ProjectMeta
            :title="$page.project.title"
            :categories="$page.project.categories"
            :year="$page.project.year"
          />
          <div class="content" v-html="$page.project.content" />
        </article>
      </Layout>
    </template>

    <template v-else>
      <!-- Layout for other projects -->
      <Layout :title="$page.project.title">
        <article class="project-post">
          <h1 v-if="$page.project.template === 'ProjectB'">hey: {{ $page.project.template }}</h1>

          <g-image class="thumbnail" :src="$page.project.thumbnail" :alt="$page.project.title" />

          <ProjectMeta
            :title="$page.project.title"
            :categories="$page.project.categories"
            :year="$page.project.year"
          />
          <div class="content" v-html="$page.project.content" />
        </article>
      </Layout>
    </template>
  </div>
</template>

<page-query>
query Project ($path: String!) {
  project: project(path: $path) {
    title
    thumbnail
    thumbnail_hover
    year
    categories
    content
    template
  }
}
</page-query>

<script>
import ProjectMeta from "@/components/ProjectMeta";

export default {
  components: {
    ProjectMeta
  },
  mounted() {
    TweenMax.from(".project-post", 0.3, {
      opacity: 0,
      delay: 0.2,
      ease: Quad.easeOut
    });

    // Instead of checking for firstChild nodes that is text elements,
    // check and see if the p tags only contains img elements and that noscript
    // generated by Gridsome.
    const contentElements = document.querySelectorAll("p");
    contentElements.forEach(
      element =>
        element.firstChild.nodeName === "#text" &&
        element.classList.add("content-text")
    );
  }
};
</script>

<style lang="scss">
@import "@/scss/nitras.scss";

.project-post {
  //padding: 0 2rem;
  @include breakpoint(xs) {
    margin: 0 $siteMarginMobile;
  }
  margin: 0 $siteMargin;
  margin-bottom: 4rem;
  background: $dark;
}
img {
  width: 100% !important;
  margin-bottom: 2rem;
}
p {
  margin: 0;
}

.parallax-img {
  height: 100%;
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

// .parallax-img {
//   background-image: url({$page.project.thumbnail});
// }

.content-text {
  padding: 4rem 0 6rem 0;
  font-size: 2rem;
  font-weight: 400;
  margin-left: 0;
  max-width: 780px;
  line-height: 1.5;

  @include breakpoint(md) {
    margin-left: $spacingDesktop;
  }
  @include breakpoint(xs) {
    flex: 0 0 $spacingMobile;
  }
}
</style>

