---
label: Portfolio Settings
hide_body: true
fields:
- name: site_title
  type: text
  config:
    required: false
  label: Site Title
- name: hero_title
  type: text
  config:
    required: false
  label: Hero Title
  description: The main H1 title of your website
- name: intro_text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Intro Text
