---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- name: intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: intro
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: services
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: services
- name: layout
  type: select
  default: Project
  config:
    required: false
    options:
    - Project
    - Project-B
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Layout
  description: The layout for each project
pages:
- projects/the-london-book-fair.md
- projects/jos.md
- projects/°-jupiter-calendar.md
- projects/molecular-gastronomy.md
