---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- name: intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: intro
- type: file
  name: thumbnail
  label: thumbnail
- name: thumnail_alt
  type: file
  config:
    maxSize: 250
  label: thumnail alt
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: services
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: services
- name: template
  type: select
  default: Project
  config:
    required: false
    options:
    - Project
    - ProjectB
    - ProjectC
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Template
  description: The template for each project
  showOnly:
    value: Project
- name: gallery
  type: image_gallery
  config: {}
  label: Gallery
pages:
- projects/°-jupiter-calendar.md
- projects/molecular-gastronomy.md
- projects/the-london-book-fair.md
