---
label: Service
hide_body: true
fields:
- type: text
  name: service_title
  label: service_title
- type: text
  name: service_information
  label: service_information
- type: list
  name: service_list
  label: service_list
- type: text
  name: service_image
  label: service_image
pages:
- services/webdesign.md
- services/grafisch-ontwerp.md
